services:
  auth-db:
    path: src/db
    dependsOn:
      # Let only auth-db deployed first, because auth-db will get credentials from developer to be reused for
      # subsequent service deployments
  auth-funcs:
    path: src/funcs
    dependsOn:
      - auth-db
  auth-api:
    path: src/api
    dependsOn:
      - auth-db
