service: auth-api
frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.11
  profile: ${param:profile}
  region: ${param:region}
  memorySize: ${param:memorySize}
  architecture: arm64
  logRetentionInDays: ${param:logRetentionInDays}
  disableRollback: ${param:disableRollback}
  deploymentBucket:
    name: darkord-sls-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
    blockPublicAccess: true
  apiGateway:
    restApiId: ${param:restApiId}
    restApiRootResourceId: ${param:restApiRootResourceId}
  environment:
    LOG_LEVEL: ${param:logLevel}
    REGION: ${param:region}
    STAGE: ${sls:stage}
    STAGE_PREFIX: ${param:stagePrefix}
    STAGE_DASH_PREFIX: ${param:stageDashPrefix}
  # For now it is sufficient to not use AWS X-Ray tracing to develop this microservice. Comment out to save cost
  # tracing:
  #   lambda: true

params:
  stage:
    profile: darkord-stage
    region: us-east-1
    memorySize: 192
    logRetentionInDays: 7
    disableRollback: true
    restApiId: ns1o12mqe1
    restApiRootResourceId: webfruxv5f
    logLevel: INFO
    stagePrefix: stage_
    stageDashPrefix: stage-
    authorizerId: pmob2d

    # Layer ARNs
    commonLayerArn: arn:aws:lambda:us-east-1:${aws:accountId}:layer:common-layer:latest
    moduleLayerArn: arn:aws:lambda:us-east-1:${aws:accountId}:layer:auth-layer:latest

    # Max action attempts
    maxSignUpAttempt: 20
    maxVerifyAttrAttempt: 3
    maxInitMfaAttempt: 1
    maxLoginAttempt: 20

  prod:
    profile: darkord
    region: ap-southeast-1
    memorySize: 384
    logRetentionInDays: 7
    disableRollback: false
    restApiId: udz4iyqum3
    restApiRootResourceId: sonnsq55fh
    logLevel: INFO
    stagePrefix: ""
    stageDashPrefix: ""
    authorizerId: "" # TODO: Deploy authorizer to production and note the ID

    # Layer ARNs
    commonLayerArn: arn:aws:lambda:ap-southeast-1:${aws:accountId}:layer:common-layer:latest
    moduleLayerArn: arn:aws:lambda:ap-southeast-1:${aws:accountId}:layer:auth-layer:latest

    # Max action attempts
    maxSignUpAttempt: 20
    maxVerifyAttrAttempt: 3
    maxInitMfaAttempt: 1
    maxLoginAttempt: 20

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 5

package:
  individually: true
  patterns:
    - "!**"

functions:
  sign-up:
    handler: sign-up/handler.handler
    package:
      patterns:
        - "sign-up/**"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${param:region}:${aws:accountId}:parameter/auth/api/token/session
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_attempt
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_user
    layers:
      - ${param:commonLayerArn}
      - ${param:moduleLayerArn}
    events:
      - http:
          method: POST
          path: /auth/user
          private: true
    environment:
      MAX_SIGN_UP_ATTEMPT: ${param:maxSignUpAttempt}
  verify-attr:
    handler: verify-attr/handler.handler
    package:
      patterns:
        - "verify-attr/**"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${param:region}:${aws:accountId}:parameter/auth/api/token/session
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_attempt
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_user
    layers:
      - ${param:commonLayerArn}
      - ${param:moduleLayerArn}
    events:
      - http:
          method: POST
          path: /auth/verify_attr
          private: true
          authorizer:
            type: TOKEN
            authorizerId: ${param:authorizerId}
    environment:
      MAX_VERIFY_ATTR_ATTEMPT: ${param:maxVerifyAttrAttempt}
  init-mfa:
    handler: init-mfa/handler.handler
    package:
      patterns:
        - "init-mfa/**"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${param:region}:${aws:accountId}:parameter/auth/api/mfa
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_attempt
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_user
    layers:
      - ${param:commonLayerArn}
      - ${param:moduleLayerArn}
    events:
      - http:
          method: POST
          path: /auth/init_mfa
          private: true
          authorizer:
            type: TOKEN
            authorizerId: ${param:authorizerId}
    environment:
      MAX_INIT_MFA_ATTEMPT: ${param:maxInitMfaAttempt}
  login:
    handler: login/handler.handler
    package:
      patterns:
        - "login/**"
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${param:region}:${aws:accountId}:parameter/auth/api/token/session
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_attempt
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - arn:aws:dynamodb:${param:region}:${aws:accountId}:table/${param:stagePrefix}auth_user
    layers:
      - ${param:commonLayerArn}
      - ${param:moduleLayerArn}
    events:
      - http:
          method: POST
          path: /auth/login
          private: true
    environment:
      MAX_LOGIN_ATTEMPT: ${param:maxLoginAttempt}

plugins:
  - serverless-better-credentials # Must be the first one in this list for this to work
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-deployment-bucket
  - serverless-latest-layer-version
