service: auth-api
frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.11
  profile: ${param:profile}
  region: ${param:region}
  memorySize: ${param:memorySize}
  architecture: arm64
  logRetentionInDays: ${param:logRetentionInDays}
  disableRollback: ${param:disableRollback}
  deploymentBucket:
    name: darkord-sls-${sls:stage}-deployment-bucket
    serverSideEncryption: AES256
    blockPublicAccess: true
  apiGateway:
    restApiId: ${param:restApiId}
    restApiRootResourceId: ${param:restApiRootResourceId}
  environment:
    LOG_LEVEL: ${param:logLevel}
    REGION: ${param:region}
    STAGE: ${sls:stage}
    STAGE_DASH_PREFIX: ${param:stageDashPrefix}
  # For now it is sufficient to not use AWS X-Ray tracing to develop this microservice. Comment out to save cost
  # tracing:
  #   lambda: true

params:
  stage:
    profile: darkord-stage
    region: us-east-1
    memorySize: 192
    logRetentionInDays: 7
    disableRollback: true
    restApiId: ns1o12mqe1
    restApiRootResourceId: webfruxv5f
    logLevel: INFO
    moduleLayerArn: arn:aws:lambda:us-east-1:${aws:accountId}:layer:auth-layer:latest
    stageDashPrefix: stage-
    maxSignUpAttempt: 20
  prod:
    profile: darkord
    region: ap-southeast-1
    memorySize: 256
    logRetentionInDays: 7
    disableRollback: false
    restApiId: udz4iyqum3
    restApiRootResourceId: sonnsq55fh
    logLevel: INFO
    moduleLayerArn: arn:aws:lambda:ap-southeast-1:${aws:accountId}:layer:auth-layer:latest
    stageDashPrefix: ""
    maxSignUpAttempt: 20

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 5

package:
  individually: true
  patterns:
    - "!**"

functions:
  sign-up:
    handler: sign-up/handler.handler
    package:
      patterns:
        - "sign-up/**"
    layers:
      - ${param:moduleLayerArn}
    events:
      - http:
          method: POST
          path: /auth/user
          private: true
    environment:
      MAX_SIGN_UP_ATTEMPT: ${param:maxSignUpAttempt}

plugins:
  - serverless-better-credentials # Must be the first one in this list for this to work
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-deployment-bucket
  - serverless-latest-layer-version
